### ISSUE TITLE
Base image is missing dependencies

### ISSUE THREAD

**Issue by mbirth** [processone/docker-ejabberd#1]
The automatically built base image (which is also available on Docker Hub) is missing some dependencies needed for some plugins, e.g. erlang-inets (for mod_http_upload) and sqlite3 support. Possibly more. See also: processone/ejabberd#1450 and processone/ejabberd#1451.

**Comment by mbirth** [comment]
deps.compile didn't compile the C module for processone/erlang-sqlite3, `priv/sqlite3_drv.so` (which requires an installed `libsqlite3.so.0`, the Alpine package it's `sqlite-libs`).

So while the Erlang module gets loaded, it still can't access sqlite databases. ejabberd throws this error:

    ** Reason: &quot;Error loading sqlite3_drv: Error loading shared library /home/p1/ejabberd/lib/sqlite3-1.1.5/priv/sqlite3_drv.so: No such file or directory&quot;

**Comment by cromain** [comment]
upgrade in progress, based on alpine v3.5. New image should be available by ejabberd 17.03 release.

**Comment by mweibel** [comment]
@cromain the repo here is updated but the image on docker hub not yet. Could you upload it please?

**Comment by urzds** [comment]
In case you were also looking at https://hub.docker.com/r/processone/ejabberd/ : That is not the official repository. https://hub.docker.com/r/ejabberd/ecs/ is.

**Comment by mweibel** [comment]
I looked at ejabberd/ecs and last time I looked was probably yesterday before the push :D ok seems to be updated now, thanks 👍

**Comment by mbirth** [comment]
With SQLite configured, the database can't be accessed because `sqlite3_drv.so` (binary driver) is still missing. (See [above](#issuecomment-276232540).)

The error message is:
```
[info] Failed open sqlite database, reason "Error loading sqlite3_drv: Error loading shared library /home/p1/ejabberd/lib/sqlite3-1.1.5/priv/sqlite3_drv.so: No such file or directory"
```
