### ISSUE TITLE
Permission settings for bind to host system?

### ISSUE THREAD

**Issue by poVoq** [processone/docker-ejabberd#10]
I am new to Docker, so maybe I am making a mistake but it seems to me there is an issue with the user permissions if you try to bind mount the config/log directory to a directory on the host system.

i.e. I am not using a docker volume (other than for the mnesia db), but would like to have direct access to the config directory from the host system. Doing so make the docker container fail to start and the logs make me assume that the issue is that the user inside the container doesn't have permission to write to these directories then.

For some other docker containers such a setup worked, but maybe they are using the root user for running the software inside?

I guess I would need to change the permissions of these folders, but since I have no idea what kind of user (UID:GID) is running inside the container, I am a bit stuck.

The reason I would like these config files accessible through the host system is mainly because I want to be able to copy SSL certs from Lets Encrypt certbot into it. Otherwise: how would I use the certbot that seems to have been added to ejabberd recently from within docker?

**Comment by cromain** [comment]
indeed, ejabberd does not run as root inside the container. I'll check this and add the needed setup in the documentation.

**Comment by poVoq** [comment]
Solved it directly in the volume (they are actually accessible in the host system under /var/lib/docker/volumes/ ), but at least in the volume both the user and group ID seems to be 9000

**Comment by cromain** [comment]
yes i confirm both UID and GID are set to 9000 (ejabberd user in that container)
this will not change in the future. This just needs to be documented.

**Comment by cromain** [comment]
note: this uid:gid is defined in Dockerfile
```
# Create directory structure and user for ejabberd
RUN addgroup ejabberd -g 9000 \
 && adduser -s /bin/sh -D -G ejabberd ejabberd -u 9000 \
 && mkdir -p /home/ejabberd/conf /home/ejabberd/database /home/ejabberd/logs \
 && chown -R ejabberd:ejabberd /home/ejabberd
```
