### ISSUE TITLE
How to format ejabberd nodes and establish s2s to form ejabberd cluster while deploying in GKE

### ISSUE THREAD

**Issue by NavinVinayagam** [processone/docker-ejabberd#103]
Hi All,
I am trying to deploy the ejabberd server in the GKE cluster. The pods will be scaled up or down based on the resource demand.
I tried this based on the information available in ejabberd document and in the readme file but It didn't work.
How to configure the ejabberd nodes in GKE and establish an s2s connection between the pods to form the ejabberd cluster?
Are there any guidelines regarding this?

**Comment by badlop** [comment]
Did you check https://github.com/processone/docker-ejabberd/issues/102#issuecomment-1635463746 https://github.com/sando38/helm-ejabberd ?
