### ISSUE TITLE
Broken Persistency of database (ecs)

### ISSUE THREAD

**Issue by wornet-mwo** [processone/docker-ejabberd#11]
If migrating from older versions to 18.01, the database can't be found. This is because 18.01 has relocated it's Database from `<database-volume>/` to `<database-volume>/ejabberd@<container-hostname>`. As the container-hostname is not persistent - this seems to me like a bug that ejabberd searches in a effectively non-constant path.

Maybe a configuration option inside `ejabberd.yml` is also enough - it's just not documented in that case.

Thanks in advance.

**Comment by cromain** [comment]
mnesia path this can be forced passed --spool option to ejabberdctl  or by defining SPOOL_DIR in ejabberdctl.cfg

**Comment by cromain** [comment]
when doing so, you will also need to force ejabberd node name (as it's used inside mnesia schema) passing --node option to ejabberdctl or by defining ERLANG_NODE in ejabberdctl.cfg

**Comment by joanlopez** [comment]
Same here for each time I re-create the container (with a mounted volume for database's data).
Solved with the solution proposed by @cromain!
Thanks a lot! :D
