### ISSUE TITLE
Build version 16.12 fails 

### ISSUE THREAD

**Issue by khba** [processone/docker-ejabberd#13]
Building version 16.12  with "./build.sh 16.12" fails at step 10/27 with following error:

**** (Mix) Could not compile dependency :stringprep, "/root/.mix/rebar3 bare compile --paths "/ejabberd/_build/prod/lib/*/ebin"" command failed. You can recompile this dependency with "mix deps.compile stringprep", update it with "mix deps.update stringprep" or clean it with "mix deps.clean stringprep"**

To reproduce the issue:

git clone https://github.com/processone/docker-ejabberd
cd docker-ejabberd/ecs
./build.sh 16.12

**Comment by cromain** [comment]
16.12 is too old.
17.12 or newer is needed. 18.03 is recommended.
