### ISSUE TITLE
Build 18.04

### ISSUE THREAD

**Issue by yokomizor** [processone/docker-ejabberd#14]
Hey,

1) **Could you please build and publish 18.04?**

2) **Is is possible to automate image creation when new releases are available?**

3) **Also, what do you think about creating images using binary distributions instead of source code?** I think it would be more consistent. When building from source code, we download dependencies using mix and rebar. Most dependencies are locked using mix.lock and rebar.config, but rebar plugins are not. Because plugins are not locked, we could end up with different results every time we rebuild images. One example of malfunction after a plugin update is https://github.com/blt/port_compiler/issues/48. While pc was broken, it was impossible to build ejabberd from source.

Thanks!

**Comment by poVoq** [comment]
Binary releases like these?

https://www.process-one.net/en/ejabberd/downloads/

**Comment by yokomizor** [comment]
Nice, thanks for the clarification.

If publishing to hex.pm is an issue, you could fetch dependencies from Github, like you are doing with rebar. I sent a PR a while ago changing this for processone/xmpp:

https://github.com/processone/ejabberd/blob/3b9e6eaa950a690a2f8e5cbf4f6dd594c1bd7dfb/mix.exs#L64

At that time I decided to change just processone/xmpp because it was the only one blocking the build process.

It would be nice to update all dependencies on mix.exs to match rebar.config. I could help with that if you agree.

**Comment by cromain** [comment]
fallback to github make things compiled with rebar AFAIR. let me investigate this and see if automation of hex.pm packages will solve things. i'll try to handle this before 18.06.

**Comment by cromain** [comment]
18.04 just pushed
