### ISSUE TITLE
CA file gets lost when using volume

### ISSUE THREAD

**Issue by stevenroose** [processone/docker-ejabberd#15]
[In the Dockerfile](https://github.com/processone/docker-ejabberd/blob/master/ecs/Dockerfile#L70), the CA certificate file is put inside the `$HOME/conf` directory. However, when mounting the conf directory as a volume (as is suggested by the Dockerfile), the content of the `conf/` directory gets lost. I think it is commonly known that a Dockerfile should not read to volume directories since it will make the content be lost when the volume is mounted.

The result is this message:
```
09:40:28.588 [warning] CA directory /etc/ssl/certs doesn't contain hashed certificate files;
configuring 'ca_path' or 'ca_file' options might help
```

**Comment by stevenroose** [comment]
I think this simple edit should do:
```diff
diff --git a/ecs/Dockerfile b/ecs/Dockerfile
index 0555e5d..0902c55 100644
--- a/ecs/Dockerfile
+++ b/ecs/Dockerfile
@@ -67,7 +67,7 @@ WORKDIR $HOME
 COPY --from=builder /ejabberd/runtime .
 COPY bin/* bin/
 COPY --chown=ejabberd:ejabberd conf conf/
-ADD --chown=ejabberd:ejabberd https://curl.haxx.se/ca/cacert.pem conf/cacert.pem
+ADD --chown=ejabberd:ejabberd https://curl.haxx.se/ca/cacert.pem /etc/ssl/certs/cacert.pem
 
 # Setup runtime environment
 USER ejabberd
```

**Comment by cromain** [comment]
bundled ejabberd config assume all these files in in conf directory anyway
ca_file: "/home/ejabberd/conf/cacert.pem"

moving to /etc/ssl/certs need to be tested. moreover, what if you need to update this file ?
mounting conf volume you can still provide your copy of cacert.pem anyway.

we'd need to test if we can provide one on /etc and allow a newer version in volume if available.

**Comment by cromain** [comment]
as said on #23, we don't plan to change the way we include cacert.pem for ejabberd. It will remain in conf directory, for consistency with all other packaging we have.
when mounting conf volume, you can still get cacert.pem from our website:
wget https://download.process-one.net/cacert.pem
this also allow you to update cacert when needed.
