### ISSUE TITLE
Certificates are not automatically reloaded

### ISSUE THREAD

**Issue by AlbanBedel** [processone/docker-ejabberd#17]
Certificates are not automatically reloaded when they are renewed, the admin has to manually trigger a config reload to have them reloaded. It seems the inotify support is missing from the docker image.

**Comment by zinid** [comment]
Acutally `inotify` is not a part of ejabberd anymore due to weird behaviour of the used Erlang wrapper. If you want the certificates to be automatically reloaded please open the corresponding issue in [ejabberd bug tracker](https://github.com/processone/ejabberd/issues).
