### ISSUE TITLE
Official docker image

### ISSUE THREAD

**Issue by gmkrab** [processone/docker-ejabberd#19]
Hi, All.
https://hub.docker.com/u/ejabberd/ -> it is official processone image? Thx!

**Comment by cromain** [comment]
yes it is. ejabberd/ecs is ejabberd Community Server for docker.

**Comment by gmkrab** [comment]
Thank you @cromain , but why PUBLIC REPOSITORY in hub? 

For example OFFICIAL:
https://hub.docker.com/_/mysql/

**Comment by cromain** [comment]
official is planned when i'll have time to work on it
