### ISSUE TITLE
It does not work with my own certificate

### ISSUE THREAD

**Issue by joanlopez** [processone/docker-ejabberd#20]
Hello guys,

I've reviewed the other certificate-related issues but no one seems to be exactly the same what's happening to me, so I decided to open this one. Sorry if not.

I have my own certificate (for `*.mydomain.com`) currently working in a production server.

Now, we want to migrate our infrastructure (at least the one for development purposes) to containers, so I'm doing some tests with the last `ecs` version.

Currently I'm mounting the entire `conf` directory. 
The problem is that I got this error when a client tries to connect with TLS:

`Failed to find a certificate matching the domain in SNI extension`

After investigating the source code of the TLS module, it seems that the certificate is not being loaded properly. However, I've checked that the container's user `ejabberd` (9000) has permission enough to load it.

So, do you guys have any idea about what's happening? Or do you know how I can debug for further information in order to discover what's failing?

Thanks a lot!
Joan :)

**Comment by joanlopez** [comment]
Could it be because the hostname is the container id and not something that matches with the domain `*.mydomain.com`?

Or it has no sense?

Thanks!

**Comment by zinid** [comment]
I think this is docker related. Once you have set some certificate you will never see "Failed to find a certificate", because this message only appears when there are no certificates found. (On tangent note: we need to improve the wording of this error message to make it clearer).

**Comment by joanlopez** [comment]
So, could it be due to the hostname?
Otherwise, what's tour suggestion?
As said, I'm sure there's no problem with permissions.
Thanks!

**Comment by cromain** [comment]
when you use your own certificate, this imply you use your own config with xmpp hostname matching your certificate. You can embed all this in your own config volume.
i assume your issue is due to hostname if you didn't changed the config file.
