### ISSUE TITLE
`cacert.pem` download from the Web

### ISSUE THREAD

**Issue by paulmenzel** [processone/docker-ejabberd#23]
Looking at `ecs/Dockerfile` (and building the image), `cacert.pem` is downloaded from the Web.

    ADD --chown=ejabberd:ejabberd https://download.process-one.net/cacert.pem conf/cacert.pem

Is that a good practice? Doesn’t the Alpine repository contain such a list of certificates?

**Comment by cromain** [comment]
we need that certificate in ejabberd's conf directory so it's available as a mountable volume and you can update it later everytime it's needed by yourself. we download it from our own website.

**Comment by cromain** [comment]
I suggest to close this, we don plan to change the way we include cacert.pem for ejabberd.
