### ISSUE TITLE
Several binaries not readable and executable for ejabberd user

### ISSUE THREAD

**Issue by paulmenzel** [processone/docker-ejabberd#24]
Running the Docker image entry point fails with `bin/ejabberdctl: Permission denied`. The reason is, that several binaries are missing the permissions to be read and executed by others.

```
ls -lh bin
total 7820
-rwxr-xr-x    1 root     root        2.4M Nov 12 15:34 beam.smp
-rwxr-xr-x    1 root     root       21.9K Nov 12 15:34 ct_run
-rwxr-xr-x    1 root     root        9.7K Nov 12 15:34 dyn_erl
-rwxrwx---    1 root     root        4.8M Nov 12 14:34 ejabberdapi
-rwxrwx---    1 root     root       10.9K Nov 12 14:34 ejabberdctl
-rwxr-xr-x    1 root     root       45.9K Nov 12 15:34 epmd
-rwxrwx---    1 root     root         196 Nov 12 14:34 erl
-rwxr-xr-x    1 root     root       13.7K Nov 12 15:34 erl_child_setup
-rwxr-xr-x    1 root     root       21.9K Nov 12 15:34 erlc
-rwxr-xr-x    1 root     root       38.5K Nov 12 15:34 erlexec
-rwxr-xr-x    1 root     root       21.9K Nov 12 15:34 escript
-rwxr-xr-x    1 root     root        9.7K Nov 12 15:34 heart
-rwxr-xr-x    1 root     root       33.9K Nov 12 15:34 inet_gethost
-rw-r--r--    1 root     root       19.5K Nov 12 15:34 no_dot_erlang.boot
-rwxr-xr-x    1 root     root        6.7K Nov 12 15:34 nodetool
-rw-r--r--    1 root     root       10.6K Nov 12 15:34 release_utils.escript
-rwxr-xr-x    1 root     root       21.7K Nov 12 15:34 run_erl
-rwxr-xr-x    1 root     root        1.1K Nov 12 15:34 start
-rw-r--r--    1 root     root       61.6K Nov 12 15:34 start.boot
-rw-r--r--    1 root     root       19.5K Nov 12 15:34 start_clean.boot
-rwxr-xr-x    1 root     root       13.7K Nov 12 15:34 to_erl
```

Is that a problem in the build image?

Adding the line below to the `Dockerfile` fixes the issue for me, that means `bin/ejabberdctl` can be executed without errors.

    RUN chmod o+rx bin/ejabberdctl bin/ejabberdapi bin/erl

**Comment by cromain** [comment]
odd I did not noticed this glitch.... maybe you generate container from Windows host which does not preserve original file attributes ? I'll enforce this in Dockerfile

**Comment by paulmenzel** [comment]
On 11/19/18 17:59, Christophe Romain wrote:
> odd I did not noticed this glitch.... maybe you generate container
> from Windows host which does not preserve original file attributes ?

No, I am using GNU/Linux and Docker 18.02.0-ce.

I ran `cd ecs; sudo ./build.sh 18.09`.

Strange, that you cannot reproduce it.

> I'll enforce this in Dockerfile
Thank you. Please reference this issue by adding

> Fixes: https://github.com/processone/docker-ejabberd/issues/24

in the commit message.

**Comment by cromain** [comment]
did you used modified local version in bin directory ? just creating container i get expected flags -rwxr-xr-x for all files. anyway, it's worth enforce these flags at creation so i'll just add chmod

**Comment by paulmenzel** [comment]
On 11/21/18 15:01, Christophe Romain wrote:
> did you used modified local version in bin directory ?

No, I did not. My umask is 007 though.

> just creating container i get expected flags -rwxr-xr-x for all
> files. anyway, it's worth enforce these flags at creation so i'll
> just add chmod

Probably, your commit ca736fb9 (Enforce local bin files mode (#24))
addresses this.
