### ISSUE TITLE
Issues with mounting database host directory

### ISSUE THREAD

**Issue by awhan** [processone/docker-ejabberd#26]
The recipe prescribed on this page https://hub.docker.com/r/ejabberd/ecs/ 
`docker run -d --name ejabberd -v $(pwd)/ejabberd.yml:/home/ejabberd/conf/ejabberd.yml -v $(pwd)/database:/home/ejabberd/database -p 5222:5222 ejabberd/ecs`
results in the container exiting immediately with status code 6.

Here is the log from the exited container
```
mkdir: can't create directory '/home/ejabberd/database/ejabberd@81c18d859392': Permission denied
/home/ejabberd/bin/ejabberdctl: cd: line 274: can't cd to /home/ejabberd/database/ejabberd@81c18d859392: No such file or directory
ERROR: can not access directory /home/ejabberd/database/ejabberd@81c18d859392
```
**Changing the permissions of the directory to 777 seems to work. Is this the idiomatic way of mounting a host directory?**
* docker image ejabberd/ecs Image ID 19475941e4c2
* docker host archlinux box
* Docker version 18.09.0-ce, build 4d60db472b

**Comment by cromain** [comment]
ejabberd UID is 9000 and GID is 9000
you need 'chown 9000:9000 database' which is better than 'chmod 777 database'.

**Comment by peterchaula** [comment]
Is there no config that can be set on the container to use a human friendly GID?

**Comment by xuruicheng96** [comment]
I think people who (are less experienced with docker) reads and follows that docker command as it will definitely run into this issue. Can we please add it to the docker hub page to remind users to change permission or ownership? Perhaps also refer https://github.com/processone/docker-ejabberd/blob/master/ecs/Dockerfile#L65 so people can read further if they want to.
Thanks for the work :)
