### ISSUE TITLE
Database always recreated at each run

### ISSUE THREAD

**Issue by paulmenzel** [processone/docker-ejabberd#27]
Deleting and creating/running a container with the same database directory mounted using a volume, a new database is created, and the users have to be recreated.

```
$ ls -ltr database/
total 52
drwxr-xr-x    2 ejabberd ejabberd         6 Nov 19 16:14 ejabberd@dfe20b018def
drwxr-xr-x    4 ejabberd ejabberd      4096 Nov 19 16:20 ejabberd@70335251a5ce
drwxr-xr-x    4 ejabberd ejabberd      4096 Nov 19 17:34 ejabberd@908f0eb7cb1c
drwxr-xr-x    4 ejabberd ejabberd      4096 Nov 19 17:42 ejabberd@974dcd37bb77
drwxr-xr-x    4 ejabberd ejabberd      4096 Nov 20 10:13 ejabberd@470e55404b5d
drwxr-xr-x    4 ejabberd ejabberd      4096 Nov 20 20:36 ejabberd@6f5f2fb7bc10
drwxr-xr-x    4 ejabberd ejabberd      4096 Nov 21 15:08 ejabberd@29e7e40483d5
drwxr-xr-x    4 ejabberd ejabberd      4096 Nov 21 16:31 ejabberd@3f03aeae441e
drwxr-xr-x    2 ejabberd ejabberd         6 Nov 21 16:34 ejabberd@5e6298af847a
drwxr-xr-x    2 ejabberd ejabberd         6 Nov 22 09:47 ejabberd@d66632fab08d
drwxr-xr-x    4 ejabberd ejabberd      4096 Nov 22 09:51 ejabberd@19aa03c635de
```

**Comment by saierd** [comment]
I have the same problem. #11 offers a solution, but I couldn't find out how `SPOOL_DIR` and `ERLANG_NODE` can bet set from an `ejabberd.yml` file. They don't occur in the documentation and an option `spool_dir` doesn't get accepted.

What is the intended way of updating the docker image without breaking the database?

**Comment by cromain** [comment]
SPOOL_DIR and ERLANG_NODE can be defined to fixed value in ejabberdctl.cfg

**Comment by saierd** [comment]
Ok, I found out where you have to enter the information.

* Run `docker exec -it <CONTAINER_NAME> bin/ejabberdctl`. The output will contain the current node name of the form `ejabberd@*****`.
* Create a file `ejabberdctl.cfg` in the `conf` directory with the following content.

```
SPOOL_DIR=/home/ejabberd/database/<NODE NAME>
ERLANG_NODE=<NODE NAME>
```

This seems to work so far and the database is reused in a new docker container. But `docker exec -it <CONTAINER> bin/ejabberdctl` does not work anymore. It prints

```
Failed RPC connection to the node <NODE NAME>: nodedown
```

even though the node actually runs and I can use it. The output also contains the fixed node name that I just put into `ejabberdctl.cfg`. Is there another option that I need to set?

**Comment by cromain** [comment]
either you implement correct node naming convention, with resolvable domains per container, either you name your node like ejabberd@localhost. I recommend the later option if you don't need cluster. I guess the name you used just does not resolve. localhost will always be resolved in a simple container setup.

**Comment by saierd** [comment]
Thank you, that works. Shouldn't this be the default for the Docker instance?

**Comment by cromain** [comment]
I don't think so, because you may need to use a swarm service and need to explicitly define the hostname of the containers you start (and likely include in same cluster).
forcing ejabberd to run in a single node instance regardless of any docker network setup is a choice which does not cover all needs.

**Comment by SharkIng** [comment]
Is this setting only available in `ejabberdctl.cfg`?
>either you implement correct node naming convention, with resolvable domains per container, either you name your node like ejabberd@localhost.

Having same issue, `Failed RPC connection to the node <NODE NAME>: nodedown`  Could you please be more specific how to do this?

**Comment by SharkIng** [comment]
I got it working, so it try to resolve the hostname but default `docker` will use the id everytime, so it's different.
add `--hostname HOSTNAME` solve the issue. I suggest should add this to the documentation under persistent data section.
