### ISSUE TITLE
[BUG] Crash due to dlsym Resource temporarily unavailable with alpine 3.10

### ISSUE THREAD

**Issue by madmath03** [processone/docker-ejabberd#46]
Hi ,

I rebuilt locally ejabberd 19.05 with this repo Dockerfile but runtime crashes:
```
dlsym: Resource temporarily unavailable
Aborted (core dumped)
```

I think it's related to upgrade to alpine 3.10 in d8972868091185cbab22289007522dcdde15b4cf since I found similar reports online and downgrading to 3.9 fixes runtime.

Similar issues: 
* https://gitlab.alpinelinux.org/alpine/aports/issues/9983
* https://github.com/c0b/docker-elixir/issues/117

**Comment by cromain** [comment]
ok, thanks, for reporting this. let's downgrade to 3.9 for now until good solution is found.
