### ISSUE TITLE
Enable Travis-CI

### ISSUE THREAD

**Issue by madmath03** [processone/docker-ejabberd#47]
The travis CI config was added in #37 but you did not enable your Travis CI repository : https://travis-ci.org/processone/docker-ejabberd

**Comment by madmath03** [comment]
By the way, I'm saying that because my fork failed to build with the latest commit : https://travis-ci.org/Monogramm/docker-ejabberd/jobs/567813713

I think it would help you if you get automatic build status here 😉

**Comment by badlop** [comment]
Apparently there was some problem enabling it in Travis. So, using your original .travis.yml file as example, I added a github action in 5d2e7890b25f8de4499642e4b1775966edfb1251 and it's now enabled.
