### ISSUE TITLE
Running `build.sh` without arguments fails in October

### ISSUE THREAD

**Issue by paulmenzel** [processone/docker-ejabberd#49]
The tag heuristic does not work as there is no release every months.

```
$ sudo ./build.sh
[…]
Step 9/30 : RUN git checkout ${VERSION/latest/HEAD}  && mix deps.get  && (cd deps/eimp; ./con
figure)
 ---> Running in 16bb55709772
error: pathspec '19.10' did not match any file(s) known to git
The command '/bin/sh -c git checkout ${VERSION/latest/HEAD}  && mix deps.get  && (cd deps/eimp; ./configure)' returned a non-zero code: 1
Error response from daemon: No such image: ejabberd/ecs:19.10
```

**Comment by badlop** [comment]
ecs/README says:
```
Build ejabberd Community Server base image for a given ejabberd version:
./build.sh 18.03
```

So, it's expected you specify an already existing release.

The script also supports the case of not providing the version, but this is expected for the case that a new release has just been tagged in the ejabberd git repository.

**Comment by paulmenzel** [comment]
> The script also supports the case of not providing the version, but this is expected for the case that a new release has just been tagged in the ejabberd git repository.

Yes, and that is what this issue was about.

Anyway, for me passing `latest` as argument worked well enough.

https://github.com/processone/docker-ejabberd/blob/8c5e758191710e03499a3e2198134acb6ad6e71d/ecs/build.sh#L12

https://github.com/processone/docker-ejabberd/blob/8c5e758191710e03499a3e2198134acb6ad6e71d/ecs/Dockerfile#L13
