### ISSUE TITLE
cannot use odbc

### ISSUE THREAD

**Issue by ChaosKid42** [processone/docker-ejabberd#50]
I try to connect this image to a database (mssql) by using odbc. However this is what I get:

```
[critical] Failed to start Erlang application 'odbc': no such file or directory: odbc.app. This usually means that ejabberd or Erlang was compiled/installed incorrectly.
```

**Comment by ChaosKid42** [comment]
I believe, I can fix it. See:

https://github.com/processone/ejabberd/pull/3125 and https://github.com/processone/docker-ejabberd/pull/51.

**Comment by mremond** [comment]
@ChaosKid42 Many thanks, I merged your changes.
