### ISSUE TITLE
** (Mix) Unknown package ex_doc in lockfile

### ISSUE THREAD

**Issue by vnthanhdv** [processone/docker-ejabberd#52]
I build and get thr error:

** (Mix) Unknown package ex_doc in lockfile
The command '/bin/sh -c git checkout ${VERSION/latest/HEAD}  && mix deps.get  && (cd deps/eimp; ./configure)' returned a non-zero code: 1

Please help me check and resolve

**Comment by mremond** [comment]
We need more details ?
How do you build ? Which commands did you type ?

Thanks!

**Comment by mremond** [comment]
Closing, as I cannot reproduce the issue.
