### ISSUE TITLE
In the README in ecs directory the ejabberdapi command does not work as written

### ISSUE THREAD

**Issue by daidoji** [processone/docker-ejabberd#57]
# Summary: 
   Very very new to ejabberd.  However, I can get this image to build (or when I pull from dockerhub directly) the command mentioned in the README: 
`docker exec -it ejabberd bin/ejabberdapi register --endpoint=http://127.0.0.1:5280/ --jid=admin@localhost --password=passw0rd` 
fails with: 
`ejabberdapi: error: user registration error for admin@localhost: Error 99: invalid character '<' looking for beginning of value`

Similar to [this issue on Stackoverflow](https://stackoverflow.com/questions/58580892/i-am-facing-errorinvalid-character-looking-for-beginning-of-value-on-reg).

# Steps to reproduce
1. pull docker image from dockerhub or build ecs from this repo with no errors
2. Attempt to run the command listed above as in the README

This error happens with the docker container running on linux or windows docker hosts.  Will be happy to provide any other details you may deem permanent. _Sorry "new issue form" mentioned in the contributor guidelines doesn't seem to have anything so I did the best I could here with the knowledge I have_

**Comment by badlop** [comment]
Hi! Some time ago I updated those instructions in the README file https://github.com/processone/docker-ejabberd/commit/eca259c24f0a35a65966e2eb3faf1e02d6516883 but they are essentially the same.

I've tried it now, using the 20.04 image, and it works correctly.

Is anybody able to reproduce the problem nowadays in some way?
