### ISSUE TITLE
LDAP support broken in 20.07

### ISSUE THREAD

**Issue by paulmenzel** [processone/docker-ejabberd#61]
Currently, LDAP does not work as reported in https://github.com/processone/ejabberd/issues/3350, and fixed in https://github.com/processone/ejabberd/commit/8aa0f7073fd4a2cd6d846ac29967f9d1aa764247#diff-6023be6004fce4718dad3dafb576d258.

No idea, if these things should be fixed up in the Docker release.

**Comment by badlop** [comment]
Well, it was committed into ejabberd repository after 20.07 was released, so the fix will be included in the next release, which I imagine will be at end of October.

In the meantime, you can rebuild the Docker image including that fix, as mentioned in https://github.com/processone/ejabberd/issues/3350#issuecomment-670060963

**Comment by paulmenzel** [comment]
Thank you for the reply. I do not know, how to easily apply that change, as the build script from here, (indirectly) just clones the repository, and the Dockerfile would probably need to be adapted to cherry-pick your referenced commit.

I work around it, by just building HEAD with `sudo ./build.sh latest`, and it worked now.
