### ISSUE TITLE
When will the Lets-Encrypt certificate be renewed?

### ISSUE THREAD

**Issue by omexlu** [processone/docker-ejabberd#67]
Hello,

How many days before expiry are the Lets-Encrypt cerificates automatically renewed in the Docker version?

Thanks in advance.

**Comment by badlop** [comment]
What certificates do you mean?
ecs/conf/server.pem expires in 2045

**Comment by omexlu** [comment]
The usual letsencrypt certs for every domain added :)

**Comment by badlop** [comment]
> ejabberd dockerized has its own renew process

Where is that process located exactly?

**Comment by omexlu** [comment]
There is nothing implemented that renews the letsencrypt certs on the docker version, therefore something like a cronjob needs to be implemented like here:

https://github.com/mailcow/mailcow-dockerized/commit/971434ddd354a87208cbee87d399fc66be3e94ff#diff-e45e45baeda1c1e73482975a664062aa56f20c03dd9d64a827aba57775bed0d3R577

**Comment by badlop** [comment]
So, you have answered your initial question, right?

**Comment by omexlu** [comment]
Yes, another description to make this manually:
https://community.mailcow.email/d/826-run-command-in-ejabberd-container/2

But can do within a cronjob to do it automatically :)

#closed
