### ISSUE TITLE
Dockerized ejabberd does not support mod_avatar

### ISSUE THREAD

**Issue by fichie23** [processone/docker-ejabberd#7]
I tried to run the latest version of `ejabberd/ecs` but it always failed to running due to an error below, 

`[critical] failed to start application 'eimp': {error, {"no such file or directory","eimp.app"}}`

Is it happen in my machine only ? or Anyone has some clues to fix this issue ? I've tried `ejabberd/ecs` version 17.12 it works perfectly.

**Comment by cromain** [comment]
For now, our container follow the same configuration than our binary installer. This means eimp is not included (ejabberd compiled with --without-graphics).
include of eimp will be tested before injection, as it requires many system dependencies.

**Comment by cromain** [comment]
fixed in latest
