### ISSUE TITLE
Provide image for arm architecture (like Raspberry Pi)

### ISSUE THREAD

**Issue by garret** [processone/docker-ejabberd#71]
Would it be possible to provide also an official image for devices like the Raspberry Pi? ejabberd is so great that it can easily run on such low-powered devices and makes so much sense when you want to self-host a local private session. 

I think this might also be easily achieved by the new docker buildx function that automatically creates images for other architectures, such as arm.

**Comment by ballerburg9005** [comment]
Yes you can build multiple architectures in one single command with Docker Buildx. I wrote a quick tutorial here:

https://ballerburg.us.to/index.php/howto-multi-architecture-builds-in-docker/

**Comment by garret** [comment]
@ballerburg9005 your reply was addressed to me or to the developers of ejabberd?

**Comment by ballerburg9005** [comment]
@garret The developers.

**Comment by ballerburg9005** [comment]
I hope the Ejabberd devs will switch to Buildx soon as suggested.

Until then I made a build myself (with instructions how to build yourself): https://hub.docker.com/repository/docker/ballerburg9005/docker-ejabberd-ecs-official-arm

**Comment by mrusme** [comment]
Any news on this? I, too, would like to use the official images on `linux/arm64/v8` but only `linux/amd64` seem to be available.

**Comment by ballerburg9005** [comment]
Check out my modified build, it explains what you have to do.

**Comment by badlop** [comment]
BTW, since [ejabberd 22.05](https://github.com/processone/ejabberd/releases/tag/22.05), a new alternative container image is available in https://github.com/processone/ejabberd/pkgs/container/ejabberd and it's built for x64 and arm64.
