### ISSUE TITLE
XEP-0156 with http lookup method

### ISSUE THREAD

**Issue by diesl** [processone/docker-ejabberd#74]
I have running an ejabberd docker container that is working fine. However, I have not found any documentation how I can use XEP-0156 with http lookup.

How can I make **/.well-known/host-meta** information available?

**Comment by diesl** [comment]
@badlop Thanks you for your quick answer. Finally I was able to work again on this issue. 

Your proposed solution is working fine for me 👍

**Comment by badlop** [comment]
By the way, [ejabberd 22.05](https://www.process-one.net/blog/ejabberd-22-05/) includes [mod_host_meta](https://docs.ejabberd.im/admin/configuration/modules/#mod-host-meta), which makes a lot easier to provide that feature

**Comment by zfkdnop** [comment]
https://compliance.conversations.im  appears to indicate XEP-0156 implementation is invalid even when it is configured correctly. I configured my node using both methods suggested above (mod_http_fileserver and mod_host_meta) and continue to receive a red X next to XEP-0156: Discovering Alternative XMPP Connection Methods (HTTP)
