### ISSUE TITLE
Updating repo to Alpine 3.14

### ISSUE THREAD

**Issue by mkl262** [processone/docker-ejabberd#78]
Hi,
Is it possible to push the new alpine:3.14 based images to docker hub?
Thanks,
Michael.

**Comment by badlop** [comment]
Yes, Alpine 3.14 is used since commit https://github.com/processone/docker-ejabberd/commit/bd19f3e33d50394e0c7330ce38862eaf7283da8f

The image for the next ejabberd release will use it.
