### ISSUE TITLE
How to add --enable-new-sql-schema in ecs Dockerfile?

### ISSUE THREAD

**Issue by kevin71020** [processone/docker-ejabberd#8]
from [SQL insert error when install ejabberd register user #2183](https://github.com/processone/ejabberd/issues/2183l) , this issue maybe as same as it.

How does add --enable-new-sql-schema in ecs Dockerfile ??
ejabberd 18.01

Add new user to ejabberd :
```
docker exec -ti example_ejabberd_1 bin/ejabberdctl register kt mac.example.com passw0rd
```

error.log :
```
ejabberd_1  | 13:43:54.923 [debug] Command 'register' execution allowed by rule 'console commands' (CallerInfo=#{caller_module => ejabberd_ctl})
ejabberd_1  | 13:43:54.923 [debug] Executing command ejabberd_admin:register with Args=[<<"kt">>,<<"mac.example.com">>,<<"passw0rd">>]

ejabberd_1  | 13:43:54.946 [error] SQL query 'Q20191286' at {ejabberd_auth_sql,162} failed: [{severity,'ERROR'},{code,<<"23502">>},{message,<<"null value in column \"server_host\" violates not-null constraint">>},{detail,<<"Failing row contains (kt, null, xqSezK+hk2SuLWM/WJEraj6wZq0=, AgzPUpIVDNJ5tX0KxBq9UjRtBTQ=, n0t2/hsb2JQ6bibR00eKFA==, 4096, 2018-01-21 21:43:50.824858).">>},{115,<<"public">>},{116,<<"users">>},{99,<<"server_host">>},{file,<<"execMain.c">>},{line,1636},{routine,<<"ExecConstraints">>}]
```

**Comment by kevin71020** [comment]
The database using [pg.sql](https://github.com/processone/ejabberd/blob/master/sql/pg.sql) not pg.new.sql.

**Comment by mremond** [comment]
Good point. The Docker file being used for new deployment, I think it should use the new schema as default.

**Comment by cromain** [comment]
this configure option has no impact on vars.config, so it's not possible to enable in using mix.
it will be enabled in 18.03, see https://github.com/processone/ejabberd/issues/2239

**Comment by cromain** [comment]
now enabled by default in ejabberd, and is a configuration option. see processone/ejabberd#2239
