### ISSUE TITLE
Load custom module into Ejabberd docker container

### ISSUE THREAD

**Issue by ailicic** [processone/docker-ejabberd#81]
I want to load this custom module into an ejabberd docker container running in docker compose.

https://github.com/skythet/ejabberd-prometheus-exporter

What is the recommended way to do that?

**Comment by badlop** [comment]
If you are already using docker-compose, I guess this is the easiest way. I tried it with ejabberd latest and works correctly. Please note, in my example, the container is named ecs_main_1:

1. First of all, get and prepare the module source code. I had to grant [permission to 9000](https://github.com/processone/docker-ejabberd/tree/master/ecs#volumes):

```
mkdir -p modules/sources/mod_prometheus/ebin
git clone https://github.com/skythet/ejabberd-prometheus-exporter.git modules/sources/mod_prometheus/src
echo "summary: \"Ejabberd metrics for Prometheus\"" > modules/sources/mod_prometheus/mod_prometheus.spec
sudo chown -R 9000:9000 modules
```

2. In your docker-compose.yml add something like this:

```yaml
    volumes:
      - ./modules:/home/ejabberd/.ejabberd-modules
```

3. Start the ejabberd docker container

4. Check the module source code is available:
```
sudo docker exec -it ecs_main_1 bin/ejabberdctl modules_available
mod_prometheus  Ejabberd metrics for Prometheus
```

5. Then compile and install it:
```
sudo docker exec -it ecs_main_1 bin/ejabberdctl module_install mod_prometheus
Module mod_prometheus has been installed.
Now you can configure it in your ejabberd.yml
```

6. As it says, configure it in ejabberd.yml. In my case I added it to request_handlers in port 5280:
```yaml
  -
    port: 5280
    ip: "::"
    module: ejabberd_http
    request_handlers:
      /admin: ejabberd_web_admin
      /metrics: mod_prometheus
```

7. Restart ejabberd. It doesn't show any specific log message.

8. Visit the URL `http://localhost:5280/metrics` It shows raw text:
```
ejabberd_memory_total_bytes{node="ejabberd@main"} 37200928
ejabberd_memory_processes_bytes{node="ejabberd@main"} 4976968
ejabberd_memory_processes_used_bytes{node="ejabberd@main"} 4976816
...
```

**Comment by ailicic** [comment]
This is working 100%. Thank you for the fast answer.

**Comment by dodziraynard** [comment]
I'm using version `24.2.0` and I have to mount the volume at `/opt/ejabberd/.ejabberd-modules/`
