### ISSUE TITLE
Cpu usage 100

### ISSUE THREAD

**Issue by hooman-mirghasemi** [processone/docker-ejabberd#82]
when docker service ejabberd restart (for example restart for renew ssl)

it use 100% of cpu for some hour. 
last time in low request time in mid night it take 4 hours!

today it start from 9AM and untile now its 4 PM . it is 100%!

i only limit it by docker-compose cpu limit to half of my server to dont get all.
we have 48 cpu core in our production machine.

and i see there are 4,268 register user in ejjaberd admin panel

why ejabberd have this behavior? is it normal behavior to have a big proccess after restart?

**Comment by mremond** [comment]
Duplicate: ejabberd#3780
