### ISSUE TITLE
0.0.0.0:5222: bind: address already in use

### ISSUE THREAD

**Issue by Yousef962** [processone/docker-ejabberd#87]
When I run this command 
```
docker run --name ejabberd -d -p 5222:5222 ejabberd/ecs
```
this is the result 
![Screenshot from 2022-06-13 10-36-17](https://user-images.githubusercontent.com/84511801/173303509-a982b9bf-26f3-4bf0-b33c-62ad8257ae33.png)

how can i fix this issue ?

**Comment by badlop** [comment]
> listen tcp4 0.0.0.0:5222: bind: address already in use

The port 5222 is already in use, probably you already have an ejabberd running in the machine.

Either stop that existing server, or tell docker to forward the contained port 5222 to your local 5233 port (for example):
```
docker run --name ejabberd -d -p 5233:5222 ejabberd/ecs
```
Of course, now you have to tell your clients to connect to port 5233

**Comment by Yousef962** [comment]
@badlop thank you, it's work
