### ISSUE TITLE
erlang-syntax-tools package is missing

### ISSUE THREAD

**Issue by relbraun** [processone/docker-ejabberd#88]
There is no possibility to compile modules with `ejabberd_sql_pt.hrl` lib because the latest version excluded the `erlang-syntax-tools` package from the Dockerfile.

**Comment by badlop** [comment]
This problem is being tracked in https://github.com/processone/ejabberd/issues/3869

**Comment by Neustradamus** [comment]
@relbraun: It has been solved?

**Comment by badlop** [comment]
This got solved with commit https://github.com/processone/ejabberd/commit/1ea53bf9405498ed7fc6656979f64f5c9aaea80e included in ejabberd 22.10, so the latest docker image should work correctly.
