### ISSUE TITLE
ecs: Alpine Linux 3.14 is not newest version

### ISSUE THREAD

**Issue by paulmenzel** [processone/docker-ejabberd#91]
https://github.com/processone/docker-ejabberd/blob/ddf9503c8ba80ce730ea1404ea7a38c5bb9c7388/ecs/Dockerfile#L40

Should it be updated to 3.16.x or even 3.17.0?

**Comment by badlop** [comment]
Right, thanks! I took the chance to also update ubuntu and some actions.

Actions logs show no error or warning, and I briefly tested manually the ecs image, it starts, can register account and login correctly, so hopefully everything else works correctly too.
